---
title: "使用R的一些技巧记录"
output: html_notebook
---


1. 循环（尤其是大循环）之前，对待矩阵、数据框等，一定要设定变量并赋值，不然耗时巨大
```{r}
d_pk=data.frame(num=1:52)
j=d_pk$num

system.time(for(i in 1:1000000){
  j
})

system.time(for(i in 1:1000000){
  1:52
})

system.time(for(i in 1:1000000){
  d_pk$num
})
```

2. 善用order进行乱序查找，威力巨大
```{r}
(i=sample(1:10,10))
(ord=order(i))
# i[ord]是升序向量，findInterval()用二分查找函数替代，复杂度从n降为log(n)
(pos=findInterval(2,i[ord]))
i[pos]
```

3. do.call()+rbind()的使用，对list进行合并
```{r}
for(i in 1:9)
  assign(paste('i_',i,sep=''),1:10+i)
do.call(rbind,mget(paste('i_',1:9,sep='')))
```

4. 利用factor进行查找
```{r}
# !!!指定levels和labels的性能提升6-7倍，只指定levels性能提升会稍高, about 11 seconds
m_c5_in2=factor(m_c2_in5,levels=m_c2[,'prm_prd'],labels=1:1326,ordered=T)
# !!!m_c5在m_c2中的序号,19600*1326, 利用names映射进行查找，about 13 seconds
names(m_c5_in2)=rep(1:2598960,10)
# attributes(m_c5_in2)
m_c5_in2=matrix(as.integer(names(sort(m_c5_in2))),19600,1326)
m_c5_in2=apply(m_c5_in2,2,sort)
```


5. 用diff比table快16倍，用sort和diff比table快2倍
```{r}
# 13.2秒
system.time({for(i in 1:100000) table(1:7)})

# 0.8秒
system.time({for(i in 1:100000) diff(1:7)})

# 4秒
system.time({for(i in 1:100000) sort(1:7)})

# 0.7秒
system.time({for(i in 1:100000) unique(1:7)})
```


6. 是否提前赋变量关系不大
```{r}
system.time({n=1:100
for(i in 1:1000000) n=1:100})


system.time(for(i in 1:1000000) n=1:100)
```

7. 矩阵需提前创建，如果每次分配耗时大
```{r}
m=matrix(nr=7,nc=5)
system.time(for(i in 1:1000000){
  m[,]=0
})

system.time(for(i in 1:1000000){
  m=matrix(nr=7,nc=5)
})
```


8. 尽量使用vector不使用matrix
```{r}
system.time(for(i in 1:1000000)
  m=matrix(nr=4,nc=13))

system.time(for(i in 1:1000000)
  n=vector('integer',52))
```


9. table()的效率很低
```{r}
j=c(1:4,1:3)
k=table(j)
system.time({
  for(i in 1:10000) k=table(j)
})

k=vector('integer',4)
system.time({
  for(i in 1:10000)
    for(l in 1:7)
      k[j[l]]=k[j[l]]+1
})
```

10. 对向量直接赋值速度最快
```{r}
a=1:4
system.time(
  {for(i in 1:2000000) a=1:4}
)

a=1:4
system.time(
  {for(i in 1:2000000) a[]=1:4}
)

a=1:4
system.time(
  {for(i in 1:2000000) a[1:4]=1:4}
)
```

11. 变量名长短与否与运行时间没有关系
```{r}
j=1
system.time({
  for(i in 1:10000000) j=1
})

dfasdsfasdsfadffdsfasdfafdasdfadfd=1
system.time({
  for(i in 1:10000000) dfasdsfasdsfadffdsfasdfafdasdfadfd=1
})
```

12. 使用向量赋值，不必使用[]
```{r}
j=1:7
system.time({
  for(i in 1:1000000) j=3:9
})

system.time({
  for(i in 1:1000000) j[]=2:8
})
```

13. for比apply快，下面的例子apply 4.3mins，for 3.5mins
```{r}
tt=Sys.time()
v_my2_in5=apply(m_bd5,1,function(x) seq5in7(v_my2,x))
Sys.time()-tt

v_my2_in5=vector('integer',nrow(m_bd5))
tt=Sys.time()
for(i in 1:nrow(m_bd5)) v_my2_in5[i]=seq5in7(v_my2,m_bd5[i,])
Sys.time()-tt
```


14. 空间换时间，新的排序方法快数倍
```{r}
system.time({
  for(i in 1:100000){
    sort.int(sample(52,5),method='shell')
  }
})
system.time({
  for(i in 1:100000){
    sort.int(sample(52,7),method='shell')
  }
})
system.time({
  for(i in 1:100000){
    sort.int(sample(52,7),method='quick')
  }
})
system.time({
  for(i in 1:100000){
    sort.int(sample(52,7),method='radix')
  }
})
system.time({
  for(i in 1:100000){
    sort.int(sample(52,7),method='auto')
  }
})
system.time({
  for(i in 1:100000){
    sort(sample(52,7))
  }
})


m413=matrix(0L,nr=4,nc=13)
system.time({
  for(i in 1:100000){
    m413[]=0L
    m413[sample(52,7)]=1L
    j=which(m413==1L)
  }
})

j=vector("integer",52)#the No.1 fastest
system.time({
  for(i in 1:100000){
    j[]=0L
    j[sample(52,7)]=1L
    k=which(j==1L)
  }
})
```




